replicaCount: 1

image:
  repository: rodrigomicrosiga/valkey-operator
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsUser: 65532
  runAsGroup: 65532
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

manager:
  leaderElect: true
  metricsBindAddress: "0"
  healthProbeBindAddress: ":8081"